export const createCategory = (name, children) => ({name, children});

export const categories = [
  createCategory('Gastronomía', [
    createCategory('Comodidades', [
      createCategory('Wi-fi Gratis'),
      createCategory('Acepta tarjetas de crédito'),
      createCategory('Incluye estacionamiento'),
      createCategory('Juegos para niños'),
      createCategory('Televisión'),
      createCategory('Acepta Reservas'),
      createCategory('Tiene servicio de delivery'),
      createCategory('Al aire libre'),
      createCategory('Acceso para silla de ruedas'),
      createCategory('Menú ejecutivo'),
    ]),
    createCategory('Restricciones alimentarias', [
      createCategory('Opciones vegetarianas'),
      createCategory('Opciones veganas'),
      createCategory('Kosher'),
      createCategory('Sin gluten'),
      createCategory('Halal'),
    ]),
    createCategory('Tipos de cocina', [
      createCategory('Comida argentina'),
      createCategory('Comida venezolana'),
      createCategory('Comida italiana'),
      createCategory('Comida francesa'),
      createCategory('Comida arabe'),
      createCategory('Comida armenia'),
      createCategory('Bar'),
      createCategory('Hamburgesería'),
      createCategory('Comida rápida'),
      createCategory('Fusión'),
      createCategory('Fusión peruana'),
      createCategory('Comida peruana'),
      createCategory('Parrilla'),
      createCategory('Pizzería'),
      createCategory('Cervecería'),
      createCategory('Cerveza artesanal'),
      createCategory('Bar de vinos'),
      createCategory('Internacional'),
      createCategory('Cafetería'),
      createCategory('Chocolatería'),
      createCategory('Comida mexicana'),
      createCategory('Pescadería'),
      createCategory('Comida española'),
      createCategory('Comida Israeli'),
      createCategory('Comida Japonesa'),
      createCategory('Comida China'),
      createCategory('Pastas'),
      createCategory('Brunch'),
      createCategory('Sandwichería'),
      createCategory('Milanesas'),
      createCategory('Sushi'),
      createCategory('Buffet libre'),
      createCategory('Picadas'),
      createCategory('Postres'),
      createCategory('Tartas'),
      createCategory('Pollo'),
    ]),
  ]),
  createCategory('Farmacias', [
    createCategory('Cuidado capilar', [
      createCategory('Shampoo'),
      createCategory('Acondicionadores'),
      createCategory('Enjuagues'),
      createCategory('Balsamos'),
      createCategory('Modelado y peinado'),
      createCategory('Reparación y tratamiento'),
      createCategory('Coloración y oxidantes'),
    ]),
    createCategory('Belleza y maquillaje', [
      createCategory('Mascaras'),
      createCategory('Labiales'),
      createCategory('Desmaquillantes'),
      createCategory('Correctores'),
      createCategory('Bases'),
      createCategory('Esmaltes'),
      createCategory('Sombras'),
      createCategory('Accesorios'),
      createCategory('Brochas y pinceles'),
      createCategory('Espejos'),
      createCategory('Esponjas y cisnes'),
      createCategory('Planchas bucleras'),
      createCategory('Secadores'),
      createCategory('Polvos y rubores'),
      createCategory('Cuidado de manos y pies'),
      createCategory('Delineadores'),
      createCategory('Quitaesmaltes'),
      createCategory('Tratamientos'),
      createCategory('Cepillos y peines'),
      createCategory('Secadores'),
      createCategory('Fijadores de esmalte'),
    ]),
    createCategory('Cuidado personal', [
      createCategory('Afeitado y depilación'),
      createCategory('Jabones y geles de ducha'),
      createCategory('Protección femenina'),
      createCategory('Protección para adultos'),
    ]),
    createCategory('Alimentos y bebidas', [
      createCategory('Alfajores'),
      createCategory('Golosinas'),
      createCategory('Cereales y granolas'),
      createCategory('Galletitas y snacks'),
      createCategory('Semillas y frutos secos'),
      createCategory('Apto para celiacos'),
      createCategory('Almacen'),
      createCategory('Bebidas'),
      createCategory('Gaseosas'),
      createCategory('Jugos'),
    ]),
    createCategory('Perfumes y fragancias', [
      createCategory('Desodorantes'),
      createCategory('Perfumes'),
      createCategory('Colonias y body spash'),
      createCategory('Bebes y niños'),
      createCategory('Sets de cofres'),
    ]),
    createCategory('Cuidado corporal', [
      createCategory('Cremas corporales'),
      createCategory('Cremas faciales'),
      createCategory('Protectores solares'),
      createCategory('Rostro'),
    ]),
    createCategory('Cuidado de la salud', [
      createCategory('Alchol'),
      createCategory('Curitas'),
      createCategory('Baño e higiene'),
      createCategory('Optica'),
      createCategory('Vendas y gasas'),
      createCategory('Termometros'),
      createCategory('Tapones para oido'),
      createCategory('Pastilleros y ordenadores'),
      createCategory('Plantillas y taloneras'),
      createCategory('Accesorios'),
      createCategory('Balanzas'),
      createCategory('Nebulizadores'),
      createCategory('Postulares'),
      createCategory('Tensiometros'),
      createCategory('Vaporizadores y humidificadores'),
      createCategory('Bolsas y geles refrigerantes'),
    ]),
    createCategory('Cuidado oral', [
      createCategory('Accesorios y adhesivos dentales'),
      createCategory('Cepillos Dentales'),
      createCategory('Cremas y enjuagues dentales'),
      createCategory('Blanqueadores'),
    ]),
    createCategory('Hogar', [
      createCategory('Nutrición y deportes'),
    ])
  ]),
  createCategory('Supermercados', [
    createCategory('Panadería y repostería', [
      createCategory('Panes'),
      createCategory('Otros panificados'),
      createCategory('Budines, magdalenas y bizcochuelos'),
    ]),
    createCategory('Carne, pollos y pescados', [
      createCategory('Carne vacuna'),
      createCategory('Pollo y granja'),
      createCategory('Carre de cerdo'),
      createCategory('Pescados'),
      createCategory('Rebozados'),
    ]),
  ]),
  createCategory('Espectaculos', [
    createCategory('Documentales'),
    createCategory('Biografico'),
    createCategory('Historico'),
    createCategory('Musical'),
    createCategory('Comedia'),
    createCategory('Infantil'),
  ]),
  createCategory('Boliches', [
    createCategory('After'),
    createCategory('Bar'),
    createCategory('Bar & boliche'),
    createCategory('Musical'),
    createCategory('Boliche'),
    createCategory('Cena show disco'),
  ]),
];
